categories: Categories
search: Search
tags: Tags
tagcloud: Tag Cloud
prev: "Prev: %s"
next: "Next: %s"
comment: Comments
archive_a: Archives
archive_b: "Archives: %s"
page: Page %d
recent_posts: Recent Posts
blogroll: Links
returntop: Return to top
readmore: READ MORE
floatmenu: Menu

menu:
    home: Home
    archives: Archives
    category: Categories
    search: Search
current_page: Current page
page_name:
    categories: (Categories)
    tags: (Tags)
    archives: (Archives)
go_back_home: Go back home
no_title: No title
